-- MySQL Script generated by MySQL Workbench
-- Thu Sep 25 19:28:42 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SchoolsDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SchoolsDB` ;
USE `SchoolsDB` ;

-- -----------------------------------------------------
-- Table `SchoolsDB`.`Departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SchoolsDB`.`Departments` ;

CREATE TABLE IF NOT EXISTS `SchoolsDB`.`Departments` (
  `department_id` INT NULL AUTO_INCREMENT,
  `department_name` VARCHAR(100) NOT NULL,
  `office_location` VARCHAR(100) NULL,
  PRIMARY KEY (`department_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SchoolsDB`.`Teachers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SchoolsDB`.`Teachers` ;

CREATE TABLE IF NOT EXISTS `SchoolsDB`.`Teachers` (
  `teacher_id` INT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `subject` VARCHAR(50) NULL,
  `department_id` INT NULL,
  `contact_info` VARCHAR(100) NULL,
  PRIMARY KEY (`teacher_id`),
  INDEX `department_id_idx` (`department_id` ASC),
  CONSTRAINT `department_id`
    FOREIGN KEY (`department_id`)
    REFERENCES `SchoolsDB`.`Departments` (`department_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SchoolsDB`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SchoolsDB`.`Students` ;

CREATE TABLE IF NOT EXISTS `SchoolsDB`.`Students` (
  `student_id` INT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `dob` DATE NULL,
  `grade_level` VARCHAR(10) NULL,
  `contact_info` VARCHAR(100) NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SchoolsDB`.`Courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SchoolsDB`.`Courses` ;

CREATE TABLE IF NOT EXISTS `SchoolsDB`.`Courses` (
  `course_id` INT NULL AUTO_INCREMENT,
  `course_name` VARCHAR(100) NOT NULL,
  `course_code` VARCHAR(20) NULL,
  `credits` INT NULL,
  `department_id` INT NULL,
  PRIMARY KEY (`course_id`),
  UNIQUE INDEX `course_code_UNIQUE` (`course_code` ASC),
  INDEX `department_id_idx` (`department_id` ASC),
  CONSTRAINT `department_id`
    FOREIGN KEY (`department_id`)
    REFERENCES `SchoolsDB`.`Departments` (`department_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SchoolsDB`.`Classroom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SchoolsDB`.`Classroom` ;

CREATE TABLE IF NOT EXISTS `SchoolsDB`.`Classroom` (
  `classroom_id` INT NULL AUTO_INCREMENT,
  `room_number` VARCHAR(10) NULL,
  `capacity` INT NULL,
  PRIMARY KEY (`classroom_id`),
  UNIQUE INDEX `room_number_UNIQUE` (`room_number` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SchoolsDB`.`Schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SchoolsDB`.`Schedule` ;

CREATE TABLE IF NOT EXISTS `SchoolsDB`.`Schedule` (
  `schedule_id` INT NULL AUTO_INCREMENT,
  `course_id` INT NULL,
  `teacher_id` INT NULL,
  `classroom_id` INT NULL,
  `day_of_week` VARCHAR(15) NULL,
  `start_time` TIME NULL,
  `end_time` TIME NULL,
  PRIMARY KEY (`schedule_id`),
  INDEX `course_id_idx` (`course_id` ASC),
  INDEX `teacher_id_idx` (`teacher_id` ASC),
  INDEX `classroom_id_idx` (`classroom_id` ASC),
  CONSTRAINT `course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `SchoolsDB`.`Courses` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `teacher_id`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `SchoolsDB`.`Teachers` (`teacher_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `classroom_id`
    FOREIGN KEY (`classroom_id`)
    REFERENCES `SchoolsDB`.`Classroom` (`classroom_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SchoolsDB`.`Enrollment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SchoolsDB`.`Enrollment` ;

CREATE TABLE IF NOT EXISTS `SchoolsDB`.`Enrollment` (
  `enrollment_id` INT NULL AUTO_INCREMENT,
  `student_id` INT NULL,
  `schedule_id` INT NULL,
  `enrollment_date` DATE NULL,
  `final_grade` VARCHAR(5) NULL,
  PRIMARY KEY (`enrollment_id`),
  INDEX `student_id_idx` (`student_id` ASC),
  INDEX `schedule_id_idx` (`schedule_id` ASC),
  CONSTRAINT `student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `SchoolsDB`.`Students` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `schedule_id`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `SchoolsDB`.`Schedule` (`schedule_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
